
package org.assignment4clientswebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientsWebService", targetNamespace = "http://assignment4ClientsWebService.org/", wsdlLocation = "http://localhost:50014/ClientsWebService.asmx?wsdl")
public class ClientsWebService
    extends Service
{

    private final static URL CLIENTSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSWEBSERVICE_EXCEPTION;
    private final static QName CLIENTSWEBSERVICE_QNAME = new QName("http://assignment4ClientsWebService.org/", "ClientsWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50014/ClientsWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSWEBSERVICE_WSDL_LOCATION = url;
        CLIENTSWEBSERVICE_EXCEPTION = e;
    }

    public ClientsWebService() {
        super(__getWsdlLocation(), CLIENTSWEBSERVICE_QNAME);
    }

    public ClientsWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSWEBSERVICE_QNAME, features);
    }

    public ClientsWebService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSWEBSERVICE_QNAME);
    }

    public ClientsWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSWEBSERVICE_QNAME, features);
    }

    public ClientsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientsWebServiceSoap
     */
    @WebEndpoint(name = "ClientsWebServiceSoap")
    public ClientsWebServiceSoap getClientsWebServiceSoap() {
        return super.getPort(new QName("http://assignment4ClientsWebService.org/", "ClientsWebServiceSoap"), ClientsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientsWebServiceSoap
     */
    @WebEndpoint(name = "ClientsWebServiceSoap")
    public ClientsWebServiceSoap getClientsWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignment4ClientsWebService.org/", "ClientsWebServiceSoap"), ClientsWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ClientsWebServiceSoap
     */
    @WebEndpoint(name = "ClientsWebServiceSoap12")
    public ClientsWebServiceSoap getClientsWebServiceSoap12() {
        return super.getPort(new QName("http://assignment4ClientsWebService.org/", "ClientsWebServiceSoap12"), ClientsWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientsWebServiceSoap
     */
    @WebEndpoint(name = "ClientsWebServiceSoap12")
    public ClientsWebServiceSoap getClientsWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://assignment4ClientsWebService.org/", "ClientsWebServiceSoap12"), ClientsWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSWEBSERVICE_EXCEPTION!= null) {
            throw CLIENTSWEBSERVICE_EXCEPTION;
        }
        return CLIENTSWEBSERVICE_WSDL_LOCATION;
    }

}
