
package edu.assignment4.adminsws.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import edu.assignment4.admisws.webservice.interfaces.ObjectFactory;
import edu.assignment4.admisws.webservice.interfaces.TracePackage;
import edu.assignment4.admisws.webservice.interfaces.TracePackageArrayList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TracePackageWebService", targetNamespace = "http://interfaces.webservice.adminsws.assignment4.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TracePackageWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/updatePackageStatusRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/updatePackageStatusResponse")
    public void updatePackageStatus(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns edu.assignment4.adminsws.webservice.interfaces.TracePackageArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/getAllPackagesRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/getAllPackagesResponse")
    public TracePackageArrayList getAllPackages();

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.assignment4.adminsws.webservice.interfaces.TracePackage
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/getPackageByIdRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/getPackageByIdResponse")
    public TracePackage getPackageById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/addPackageRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/addPackageResponse")
    public void addPackage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/deletePackageRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/deletePackageResponse")
    public void deletePackage(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/trackPackageRequest", output = "http://interfaces.webservice.adminsws.assignment4.edu/TracePackageWebService/trackPackageResponse")
    public void trackPackage(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
