
package edu.assignment4.adminsws.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TracePackageWebServiceImplService", targetNamespace = "http://webservice.adminsws.assignment4.edu/", wsdlLocation = "http://localhost:8888/adminsws/tracepackage?wsdl")
public class TracePackageWebServiceImplService
    extends Service
{

    private final static URL TRACEPACKAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACEPACKAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TRACEPACKAGEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.adminsws.assignment4.edu/", "TracePackageWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/adminsws/tracepackage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACEPACKAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TRACEPACKAGEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TracePackageWebServiceImplService() {
        super(__getWsdlLocation(), TRACEPACKAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TracePackageWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACEPACKAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TracePackageWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TRACEPACKAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public TracePackageWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACEPACKAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public TracePackageWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TracePackageWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TracePackageWebService
     */
    @WebEndpoint(name = "TracePackageWebServiceImplPort")
    public TracePackageWebService getTracePackageWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.adminsws.assignment4.edu/", "TracePackageWebServiceImplPort"), TracePackageWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TracePackageWebService
     */
    @WebEndpoint(name = "TracePackageWebServiceImplPort")
    public TracePackageWebService getTracePackageWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.adminsws.assignment4.edu/", "TracePackageWebServiceImplPort"), TracePackageWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACEPACKAGEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TRACEPACKAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TRACEPACKAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
